- name: Setup new machine
  hosts: vm
  gather_facts: true
  vars:
    sshkey_create: False
    sshkey_type: rsa
  roles:
    - user_config
    - sshkey
    - pkgs
    - dotfiles
    - eideticom-scripts
    - dmesg
